### PR TITLE
Release 0.8.0

### PR DESCRIPTION
**Pull request by DerGuteMoritz**
Lemme know if I missed anything!

### CODE REVIEW

**Review by arnaudgeiser — APPROVED** [review]

**Comment by DerGuteMoritz** [comment]
> Did you check that the new Netty didn't break anything in Aleph?

At least the tests for [the PR that bumped Netty](https://github.com/clj-commons/aleph/pull/725) went through without a hitch on first try and so did they [after hitting `master`](https://github.com/clj-commons/aleph/commit/cb0a22d75ee65a7e8f888dfe61d8799a7819df56) :shrug: [The last run](https://app.circleci.com/pipelines/github/clj-commons/aleph/692/workflows/806139fd-3bfa-4130-a423-b0d62371148b/jobs/678/parallel-runs/0/steps/0-107) only failed with

```
    java.lang.RuntimeException: Gave up awaiting leak probe. Try increasing `aleph.resource-leak-detector/max-probe-gc-runs`
```

which is a somewhat expected flake. In [the run before that](https://app.circleci.com/pipelines/github/clj-commons/aleph/692/workflows/5ec904b0-7d02-46a9-875c-fc5ef2bb75a5/jobs/677/parallel-runs/0/steps/0-107) there were two failures:

```
ERROR in (test-request-timeout) (client.clj:520)
- http2
expected: (thrown? TimeoutException (clojure.core/deref (http-get "/slow" {:request-timeout 5})))
```

Which is a timing-sensitive test so I can see how that one could flake, too. The other one is a bit strange:

```
lein test :only aleph.http-test/test-bulk-requests
31513 tid=91 WARN DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at io.netty.buffer.UnpooledDirectByteBuf.setBytes(UnpooledDirectByteBuf.java:570)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:821)
        at io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:636)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:356)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at manifold.executor$thread_factory$reify__761$f__762.invoke(executor.clj:71)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)

ERROR in (test-bulk-requests) (client.clj:520)
Uncaught exception, not in assertion.
expected: nil
36186 tid=31 WARN DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000000401
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:107)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:351)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:245)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:451)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1349)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1389)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at manifold.executor$thread_factory$reify__761$f__762.invoke(executor.clj:71)
        at clojure.lang.AFn.run(AFn.java:22)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
  actual: clojure.lang.ExceptionInfo: connection was closed after 0.024 seconds
{:request {:path "/string", :user-info nil, :pool-timeout 10000.0, :pool #object[io.aleph.dirigiste.Pool 0x1d19a83d "io.aleph.dirigiste.Pool@1d19a83d"], :throw-exceptions? false, :request-url "https://localhost:8082/string", :server-port 8082, :request-timeout 10000.0, :uri "/string", :server-name "localhost", :query-string nil, :scheme :https, :request-method :get}}
 at aleph.http.client$rsp_handler$handle_response__7322.invoke (client.clj:520)
    manifold.deferred$eval2006$chain_SINGLEQUOTE____2027.invoke (deferred.clj:883)
    manifold.deferred$eval2006$subscribe__2007$fn__2012.invoke (deferred.clj:849)
    manifold.deferred.Listener.onSuccess (deferred.clj:345)
    manifold.deferred.Deferred/fn (deferred.clj:524)
    manifold.deferred.Deferred.success (deferred.clj:524)
    manifold.deferred$success_BANG_.invokeStatic (deferred.clj:369)
    manifold.deferred$success_BANG_.invoke (deferred.clj:366)
    aleph.http.http2$client_handler$reify__6947.channelInactive (http2.clj:1151)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:305)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:281)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive (AbstractChannelHandlerContext.java:274)
    io.netty.handler.stream.ChunkedWriteHandler.channelInactive (ChunkedWriteHandler.java:152)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:303)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:281)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive (AbstractChannelHandlerContext.java:274)
    io.netty.handler.logging.LoggingHandler.channelInactive (LoggingHandler.java:206)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:303)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:281)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive (AbstractChannelHandlerContext.java:274)
    io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive (DefaultChannelPipeline.java:1402)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:301)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:281)
    io.netty.channel.DefaultChannelPipeline.fireChannelInactive (DefaultChannelPipeline.java:900)
    io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe$2.run (AbstractHttp2StreamChannel.java:797)
    io.netty.util.concurrent.AbstractEventExecutor.runTask (AbstractEventExecutor.java:173)
    io.netty.util.concurrent.AbstractEventExecutor.safeExecute (AbstractEventExecutor.java:166)
    io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks (SingleThreadEventExecutor.java:469)
    io.netty.channel.nio.NioEventLoop.run (NioEventLoop.java:566)
    io.netty.util.concurrent.SingleThreadEventExecutor$4.run (SingleThreadEventExecutor.java:994)
    io.netty.util.internal.ThreadExecutorMap$2.run (ThreadExecutorMap.java:74)
    manifold.executor$thread_factory$reify__761$f__762.invoke (executor.clj:71)
    clojure.lang.AFn.run (AFn.java:22)
    io.netty.util.concurrent.FastThreadLocalRunnable.run (FastThreadLocalRunnable.java:30)
    java.lang.Thread.run (Thread.java:750)
```

@KingMob Can you make sense from that?


>  I usually read through the Netty changelog to see if there's anything relevant.

Had done that, too, but nothing seemed particularly relevant. I just checked the detailed list via their issue tracker but it seems all pretty much like small bug fixes here and there, nothing sticks out that could explain increased flakiness on our end.


> This is part of why I dislike the current existence of low-quality CVEs that constantly encourages people to bump up deps; there's real work to do just to check that nothing breaks.


Indeed :confounded: On the positive side, it has pushed us towards dropping some huge CVE-prone dependencies (*cough* `firebase-admin-sdk` *cough*) :smile: 

> Hope it's just a glitch in the matrix.

I just re-ran the test job and now it passed. My current guess is that it was just a particularly busy day at CircleCI and that Aleph's test suite isn't very resilient against that...

**Comment by DerGuteMoritz** [comment]
Gonna merge this one now already but we can continue the discussion of course.

**Comment by KingMob** [comment]
It may be best to just disable the flaky tests until they can be made reliable.

**Comment by DerGuteMoritz** [comment]
> It may be best to just disable the flaky tests until they can be made reliable.

Hm I don't think there is a way to make them 100% reliable under all conditions, given that they are timing-sensitive (just not sure about the `test-bulk-requests` case, yet). So if the CI runner is just very busy, timings might be off enough to make tests flake. However, I'll look into adding a knob for controlling how much leeway timing-sensitive tests get which we could then use to give more leeway in CI (at the cost of tests potentially taking longer to run) while locally, one could use a lower setting.

**Comment by KingMob** [comment]
The problem with that kind of flakiness is if the timing constraints are loosened too much, it results in a useless test that won't fail even if there's a real performance regression. If you tighten it, you get false positive like we currently have. And with multiple test environments, it's possible for both of those to be problems at the same time!

One solution is to separate those tests into their own CI action, and downgrade their failure to that of a warning, so at least they won't get mixed up with reliable tests.

**Pull request merged**
