### PR TITLE
Update examples and docs

### LINKED ISSUE #629: Update examples and docs
First, while the aleph.io literate documentation site is cool, we aren't currently keeping it up-to-date, and would have to bug Zach for access if we wanted to. On top of that, in recent years, cljdoc.org has emerged as the standard bearer for clj documentation. I'd like to convert the examples and literate docs into articles or something so that users of cljdoc.org can read them.

Along with that, the current routing in `examples` is based off Compojure, which is not very popular these days. I'd like to switch to reitit, or something more data-driven.

To do:
- [x] (Optional) Get local cljdoc building working, if you haven't before
- [x] Bring aleph.io docs to cljdoc.org
- [x] Convert example routing to reitit
- [x] Fix the examples' to follow the clojure style guide

### PR DESCRIPTION
**Pull request by arnaudgeiser**
Fixes #629

### CODE REVIEW

**Review by KingMob — APPROVED** [review]
👍🏻 Nice work!

Have you tested it with [local cljdoc](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally-author.adoc)? Fair warning, it can get a bit tricky. I have some scripts for deps.edn-based repos, but not lein.

**Comment by arnaudgeiser** [comment]
> Have you tested it with [local cljdoc](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally-author.adoc)? Fair warning, it can get a bit tricky. I have some scripts for deps.edn-based repos, but not lein.

Happy to hear that, because it took me a while to understand how to work with a local cljdoc.
The documentation is great, but I didn't get it initially.
Yet, it has been tested.

Please note I had an heavy hand with `^:no-doc` here.

Here is the result :

image

image

image

image

image

image

image

image

**Comment by arnaudgeiser** [comment]
Please let a thumbs up on this comment if you are fine with my choice.
I removed more than 50% of the functions on the documentation, and the whole `http/server.clj`, `http/core.clj`, `http/client.clj`, `http/encoding.clj` namespaces.

I not able to remove `->Cookie` from the documentation as potemkin `p/derived-map` is not supporting metadata so far.

**Comment by arnaudgeiser** [comment]
Actually, it's just documentation.
If I've been too aggressive, we'll change it back.
Merging.

**Pull request merged**
