### PR TITLE
Fix websocket-upgrade-request? for Firefox WebSocket upgrade requests.

### LINKED ISSUE #561: websocket-upgrade-request? doesn't detect connection upgrade when there are other tokens
Firefox sometimes (always?) sends `keep-alive` as well as `Upgrade` in the `Connection` request header when it tries a WebSocket upgrade request, so `websocket-upgrade-request?` as written does not return true for Firefox WebSocket upgrade requests.

### PR DESCRIPTION
**Pull request by xorgy**
Fixes #561

### CODE REVIEW

**Comment by slipset** [comment]
Thanks a lot xorgy. Could you please also provide a test which shows that this doesn't break existing functionality, ie that it works when only sending "Upgrade" in the connection header, as well as when sending "keep-alive,Upgrade"?

**Comment by xorgy** [comment]
> Thanks a lot xorgy. Could you please also provide a test which shows that this doesn't break existing functionality, ie that it works when only sending "Upgrade" in the connection header, as well as when sending "keep-alive,Upgrade"?

Sure, I'll write a test for it.

**Comment by xorgy** [comment]
Let me know if the test I've added is satisfactory, I can squash it in.

**Review by slipset — APPROVED** [review]
LGTM

No need to squash, I'll do a squash merge here. Thanks!

**Comment by xorgy** [comment]
Thank you as well.

**Pull request merged**
